image: Visual Studio 2019

environment:
  QTDIR: C:\Qt\5.15.2\mingw81_64

install:
  - set PATH=%QTDIR%\bin;%QTDIR%\..\..\Tools\mingw810_64\bin;C:\Program Files (x86)\NSIS\;%PATH%

build_script:
  - cd src/
  - qmake UltraStar-Creator.pro -spec win32-g++
  - mingw32-make -j4

after_build:
  - makensis ../setup/win64/UltraStar-Creator.nsi

artifacts:
  - path: bin/release
    name: UltraStar-Creator-portable
    type: zip
  - path: bin/UltraStar-Creator*-setup.exe
