environment:
  QTDIR: C:\Qt\5.8\mingw53_32

install:
  - cmd: set PATH=%QTDIR%\bin;%QTDIR%\..\..\Tools\mingw530_32\bin;C:\Program Files (x86)\NSIS\;%PATH%

build_script:
  - cmd: >-
      cd src/
      
      qmake usc.pro -spec win32-g++
      
      mingw32-make

after_build:
  - cmd: >-
      makensis ../setup/win32/usc.nsi

artifacts:
  - path: bin/release
    name: UltraStar-Creator-portable
    type: zip
  - path: bin/UltraStarCreator*-setup.exe
