environment:
  QTDIR: C:\Qt\5.12.2\mingw73_64

install:
  - set PATH=%QTDIR%\bin;%QTDIR%\..\..\Tools\mingw730_64\bin;C:\Program Files (x86)\NSIS\;%PATH%

build_script:
  - cd src/
  - qmake UltraStar-Creator.pro -spec win32-g++
  - mingw32-make -j4

after_build:
  - makensis ../setup/win32/UltraStar-Creator.nsi

artifacts:
  - path: bin/release
    name: UltraStar-Creator-portable
    type: zip
  - path: bin/UltraStar-Creator*-setup.exe
